### ISSUE TITLE
Desmos Tip Bot UI

### ISSUE THREAD

**Issue by Rooty2020** [forbole/UIUX#102]

**Comment by Rooty2020** [comment]
@nicoletting 
please update UI 
if possible, preferably finish it by the end of March 7 (Tmr)
thanks

**Comment by nicoletting** [comment]
Desktop UI is ready, please check🙇🏻‍♀️ @RiccardoM 
- [image download here](https://drive.google.com/drive/u/3/folders/1zwSLN2UJRWS3PayFopJM_xFwUXtN7o_2)
- [boardcasting animation download here](https://drive.google.com/drive/folders/1y2LPvQIpDkk-PWXC-knlyO6p98X3FvVU?usp=sharing)

**Comment by rmontagnin** [comment]
Thank you @nicoletting, looks great!
