### ISSUE TITLE
bigdipper.live 2.0_UI design

### ISSUE THREAD

**Issue by Rooty2020** [forbole/UIUX#18]

**Comment by Rooty2020** [comment]
@ryuash 
Please write down your requirements here, thanks

**Comment by ryuash** [comment]
Supported networks section:
![image](https://user-images.githubusercontent.com/42913823/140743165-7f0f0fde-d135-491d-997b-d8a10b2a3c77.png)

Requirements:
- Able to display different networks for the same chain (testnet, mainnet, devnet etc)
- Able to display multiple hosts for the same network (ex - other people might host an explorer for desmos big dipper and we would like to display that on our website too). So we would have something like `desmos-mainnet - forbole`, `desmos-mainnet - rooty`

---

Would prefer if footer stays the same
