### ISSUE TITLE
【UI Update】Tx list

### ISSUE THREAD

**Issue by Rooty2020** [forbole/UIUX#21]
Feedbacks
> The transaction list needs better separation between transactions i.e. not obvious whether the amount belongs to the tx# above or below

> A little bit complicated to find out my transaction history.

![Screenshot 2021-11-18 at 1.58.09 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/dfa02362-ef32-4f76-9787-15966fd9ee10)

**Comment by nicoletting** [comment]
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/480afa76-cb1c-4c63-b8d9-255ca4db6ca5)
