### ISSUE TITLE
[UI Update] Tx tab color

### ISSUE THREAD

**Issue by Rooty2020** [forbole/UIUX#22]
Update the tx tab color for white and dark theme
![Screenshot 2021-10-07 at 11.51.55 AM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/32fa955a-dbd7-4e5c-9aaa-f6e6c2bf9db7)

TX type
-Staking
Delegate
Redelegate
Undelegate

-Transfer
Receive
Send
Multisend

-Distribution
Staking rewards
Commissions
Set Reward Address

-Governance
Submit proposal
Deposit
Vote

-Slashing
Unjail

**Comment by nicoletting** [comment]
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/77859c5d-00f8-4f48-bd24-cc38dfa5d728)
