### ISSUE TITLE
URGENT- Update Images

### ISSUE THREAD

**Issue by Rooty2020** [forbole/UIUX#24]
@nicoletting Please change Forboles Ventures to Forbole Ventures.
After completing this task, please send the updated image to Rachel.

![Screenshot 2021-11-08 at 5.06.22 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/a7799bcd-b303-4dfa-88c7-3ee89c74d497)

**Comment by Rooty2020** [comment]
@nicoletting 
the image with SVG format would be great.

**Comment by nicoletting** [comment]
https://drive.google.com/drive/folders/1x4XdLVYfmxxdramMaN6OMuxkVOWx1cWR?usp=sharing
