### ISSUE TITLE
[iOS] Setting icon is missing

### ISSUE THREAD

**Issue by Rooty2020** [forbole/UIUX#40]
Software Version:15.1
Mobile Device: iPhone 11
DPM version: 0.0.5(0.1.7)

![Screenshot 2021-11-25 at 9.48.57 AM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/d5ffedec-dae3-478f-8e1b-89d6ec5f2eba)

- Setting icon is missing

- The text of button should be # Poppins Medium 16PX

**Comment by Rooty2020** [comment]
@bragaz @manu0466

**Comment by manu0466** [comment]
This feature is not yet implemented.  
I have created an issue to keep track of that: https://github.com/desmos-labs/dpm/issues/38
