### ISSUE TITLE
[iOS] visual (color, icon, fonts etc)

### ISSUE THREAD

**Issue by Rooty2020** [forbole/UIUX#42]
Software Version:15.1
Mobile Device: iPhone 11
DPM version: 0.0.5(0.1.7)

- The menu icon seems to be compressed.
- Can we move the navigation bar down a bit?

- Change copy icon color to white (Light mode)

- Remove colon (:)

-The font of Amount and nickname should be  #Poppins Medium 22 px

![Screenshot 2021-11-25 at 10.20.46 AM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/b75780ea-5313-4d00-a752-f98bf565e385)

**Comment by Rooty2020** [comment]
@bragaz @manu0466

**Comment by nicoletting** [comment]
Another visual issue:

- should use the correct image in dark mode**
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/2e428122-31c6-4c60-afb7-26ba033b6b4d)

the UI should be like:
![preview.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/93b38a0c-e018-44a5-a904-9584fa128573)

**Comment by manu0466** [comment]
Copied to https://github.com/desmos-labs/dpm/issues/34
