### ISSUE TITLE
[iOS] Add account flow is not correct

### ISSUE THREAD

**Issue by Rooty2020** [forbole/UIUX#43]
When the user taps the add account button, the flow should be https://www.figma.com/proto/dJaV50hqiOkraw3J1HQIxY/DPM-1.0?page-id=1858%3A24110&node-id=1858%3A24745&viewport=241%2C48%2C0.31&scaling=scale-down&starting-point-node-id=2751%3A44183&show-proto-sidebar=1

add account---enter wallet password ---import account

**Comment by Rooty2020** [comment]
@bragaz @manu0466

**Comment by manu0466** [comment]
@Rooty2020 @nicoletting In order to have that flow i have to store the user mnemonic in the device storage. 
For security reason  is beter to only store the key pair derived from that and ask the user to retype the mnemonic.
