### ISSUE TITLE
[iOS] incorrect UI of Connect Chain

### ISSUE THREAD

**Issue by nicoletting** [forbole/UIUX#44]
- Since it is a button, please make it looks more like a button by adding a card behind it. 

the UI:
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/9f5fd196-181d-4a2a-b3a6-2c311bcc571f)

The original design:
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/6761da69-9239-4c12-9870-e669887f59d0)

**Comment by nicoletting** [comment]
@bragaz @manu0466

**Comment by manu0466** [comment]
Copied to https://github.com/desmos-labs/dpm/issues/35
