### ISSUE TITLE
Design Shared Images 

### ISSUE THREAD

**Issue by Rooty2020** [forbole/UIUX#69]
Design shared images for Forbole Ventures and Demsos websites

Requirements:
Facebook:1200 * 630
Twitter: 1012 * 530

https://www.figma.com/file/HIowGnwyAMIcWvqKBOq3Bv/Shared-Images?node-id=0%3A1

**Comment by nicoletting** [comment]
@rachelhox The images are ready.
https://drive.google.com/drive/folders/1auIMG4kOXiO--sLI7Ntk8vz5t0pwEEjE?usp=sharing
